//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Description
    {
        public int ID { get; set; }
        public Nullable<int> CBK_CODES { get; set; }
        public string BANK_ID { get; set; }
        public string BANK_NAME { get; set; }
        public string SORT_CODE { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
