//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banksefficiency2
    {
        public System.DateTime ENDDATE { get; set; }
        public string BANK { get; set; }
        public decimal PCTEFF { get; set; }
        public string RESPONSECODE { get; set; }
        public int WEEKLYRANK { get; set; }
        public string ORIENTATION { get; set; }
    }
}
