//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMonAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BIDATABASEEntities1 : DbContext
    {
        public BIDATABASEEntities1()
            : base("name=BIDATABASEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bank_Description> Bank_Description { get; set; }
        public DbSet<Bank> Banks { get; set; }
        public DbSet<Banks2> Banks2 { get; set; }
        public DbSet<banksefficiency> banksefficiencies { get; set; }
        public DbSet<banksefficiency2> banksefficiency2 { get; set; }
        public DbSet<INTERFACE_UPTIME> INTERFACE_UPTIME { get; set; }
        public DbSet<LINK_AVAILABILITY> LINK_AVAILABILITY { get; set; }
        public DbSet<WEEKLY_POSITION> WEEKLY_POSITION { get; set; }
        public DbSet<NetworkReport> NetworkReports { get; set; }
    }
}
