//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINK_AVAILABILITY
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string BANK_CODE { get; set; }
        public Nullable<int> RATE { get; set; }
        public Nullable<int> RANK { get; set; }
    }
}
