//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogID { get; set; }
        public System.DateTime LogDateIn { get; set; }
        public string LogRequest { get; set; }
        public int Method { get; set; }
        public string LogRequestToAPI { get; set; }
        public Nullable<System.DateTime> LogRequestToAPIDate { get; set; }
        public string LogResponseFromAPI { get; set; }
        public Nullable<System.DateTime> LogResponseFromAPIDate { get; set; }
        public string LogResponse { get; set; }
    }
}
