//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyAnalytic
    {
        public int AnalyticsID { get; set; }
        public System.DateTime AnalyticsDate { get; set; }
        public string BankCode { get; set; }
        public double FailureRateIn { get; set; }
        public int VolumeIn { get; set; }
        public double FailureRateOut { get; set; }
        public int VolumeOut { get; set; }
    }
}
