//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyRating
    {
        public int RANKINGID { get; set; }
        public string RECEIVERS_SORT_CODE { get; set; }
        public decimal PCTEFF { get; set; }
        public int WEEKLYRANK { get; set; }
        public string RESPONSECODE { get; set; }
        public string SENDERS_SORT_CODE { get; set; }
    }
}
